server:
  port: 3000

db:
  type: 'mongodb'
  port: 27017
  database: 'applicationDB'

jwt:
  expiresIn: 43200
  secret: '123'

mail:
  host: 'smtp.kinghost.net'
  port: 587
  user: contato@uuebi.com
  password: m5cycbr
